log-level: FINE
webhook:
  enabled: false
  port: 8443
  externalUrl: https://123.45.67.89:$port
  internalUrl: https://123.45.67.89:$port
  certificatePublicKeyPath: cert/public_cert.pem
  certificateStorePath: cert/keystore.jks
  certificateStorePassword: secret
modules:
  - com.annimon.testbot.TestBot