log-level: FINE
webhook:
  enabled: false
  port: env(PORT:8443)
  externalUrl: https://123.45.67.89:$port
  internalUrl: https://123.45.67.89:$port
  certificatePublicKeyPath: cert/public_cert.pem
  certificateStorePath: cert/keystore.jks
  certificateStorePassword: env(STORE_PASSWORD)
modules:
  - com.annimon.testbot.TestBot