log-level: FINE
webhook:
  enabled: false
  port: env(PORT:8443)
  #### For Heroku
  # externalUrl: https://yourappname.herokuapp.com/
  #### For your web server
  # externalUrl: https://123.45.67.890:$port
  externalUrl: env(URL)
  internalUrl: http://0.0.0.0:$port
  # For self-signed certificates (optional)
  keystorePath: cert/keystore.jks
  keystorePassword: env(KEYSTORE_PASSWORD)
modules:
  - com.annimon.testbotkt.TestBot